### ISSUE TITLE
Load Error on build

### ISSUE THREAD

**Issue by svendroid** [dmathieu/glynn#34]
I get following error when executing glynn. Do you have an idea if its an glynn bug or an error in my jekyll-blog?
I'm using jekyll-2.5.0 and glynn 1.1.0.

    Configuration file: /Users/sven/development/gipfelbuch/_config.yml
    Building site: /Users/sven/development/gipfelbuch -> /Users/sven/development/gipfelbuch/_site
    Configuration file: /Users/sven/development/gipfelbuch/_config.yml
    /Users/sven/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-2.5.0/lib/jekyll/site.rb:150:in `read': cannot load such file -- jekyll/layout_reader (LoadError)
        from /Users/sven/.rvm/gems/ruby-2.0.0-p247/gems/jekyll-2.5.0/lib/jekyll/site.rb:49:in `process'
        from /Users/sven/.rvm/gems/ruby-2.0.0-p247/gems/glynn-1.1.0/lib/glynn/jekyll.rb:15:in `build'
        from /Users/sven/.rvm/gems/ruby-2.0.0-p247/gems/glynn-1.1.0/bin/glynn:28:in `<top (required)>'
        from /Users/sven/.rvm/rubies/ruby-2.0.0-p247/bin/glynn:23:in `load'
        from /Users/sven/.rvm/rubies/ruby-2.0.0-p247/bin/glynn:23:in `<main>'

**Comment by dmathieu** [comment]
This looks like a jekyll error. It's unable to find your `layout_reader` local file.
