### ISSUE TITLE
Windows Compatibility Issue

### ISSUE THREAD

**Issue by amorvita** [dmathieu/glynn#41]
From Issue #3

> That reason is simple. To check if a file is binary (in which case it needs to be sent with the
> putbinaryfile method) or is text (in which case it needs to be sent with the puttextfile method),

Why do you use puttextfile? Is there no problem that text file is sent with putbinary method?

I think that there is no need to use is_bin method.

**Comment by dmathieu** [comment]
This was 5 years ago :smile:
Are you able to get it to work with putbinary file only? If so, feel free to send a pull request.

**Comment by amorvita** [comment]
#42 

Thanks

**Comment by dmathieu** [comment]
061a538db07c90cba989ba6d1735908055c8bd28
