### ISSUE TITLE
Is auto-deploy possible with Jekyll?

### ISSUE THREAD

**Issue by NginUS** [dmathieu/glynn#43]
I have the following in my site/project 's root dir in a "_config.yml" file:

include: [.htaccess]
timezone: America/New_York
baseurl: http://domain.tld

...And I was wondering if there's a way to automatically have glynn upload the built files similarly to how I automatically set the timezone & include the '.htaccess' file in the build via some "_config.yml" file option.

**Comment by dmathieu** [comment]
Glynn will compile your jekyll site and send the files via FTP, that it all.
Any auto-deploy needs to use a third-party platform (that can be Travis-CI for example) to execute the command.
