### ISSUE TITLE
glynn: command not found

### ISSUE THREAD

**Issue by guayom** [dmathieu/glynn#44]
I installed the gem and then tried to run glynn, but I get the following error:
-bash: glynn: command not found

**Comment by alistaircom** [comment]
Path issue it sounds like. What happens when you try this command:

    which glynn

**Comment by dmathieu** [comment]
Closing as stale.

**Comment by makingculture** [comment]
I'm having the same issue, I'm getting command not found: glynn

I am using zsh rather than bash, would this be an issue?

$ which glynn  
glynn not found

**Comment by dmathieu** [comment]
This looks like an issue with your ruby installation and your PATH not including the path to gem executables.

**Comment by makingculture** [comment]
Thanks for the reply, I have ruby installed locally at /Users/myname/.rbenv/shims/ruby and running ruby 2.2.3

My PATH is /Users/myname/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Is it better to have this installed at PATH /usr/local/bin/ ?

I use rbenv with bundler installed via homebrew.

**Comment by makingculture** [comment]
Hi I decided to uninstall rbenv and bundler and just run ruby and gems via /usr/local/bin/ using sudo.

Probably not the best approach but I have Jekyll and Glynn now working.

**Comment by dmathieu** [comment]
You would need to add `/Users/myname/.rbenv/bin` to your PATH.
