### ISSUE TITLE
Error when I run glynn

### ISSUE THREAD

**Issue by c-hris** [dmathieu/glynn#45]
I followed the readme and configured ftp_host and ftp_dir in jekyll _config.yml but when i ran glynn i got the following error: I use Windows

`Successfully generated site
Sending site over FTP (host: ftp.site.com, port: 21, ftps: false)
Connected to server. Sending site
 -> assets
 -> css
 -> layouts
 -> footer.sass
c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/lib/glynn/file.
rb:5:in ``': No such file or directory - file c:/Users/user/desktop/site/
_site/assets/css/layouts/footer.sass (Errno::ENOENT)`

**Comment by c-hris** [comment]
Any suggestion?

**Comment by dmathieu** [comment]
This should have been fixed by 061a538db07c90cba989ba6d1735908055c8bd28
Could you try installing the gem from git master? If that properly fixes it for you, I'll release a new version.

**Comment by c-hris** [comment]
`Configuration file: c:/Users/user/desktop/folder/_config.yml
Building site: c:/Users/user/desktop/folder-> c:/Users/user/desktop/folder/_site Configuration file: c:/Users/user/desktop/folder/_config.yml
Successfully generated site
Sending site over FTP (host: ftp.site.com, port: 21, ftps: false Connected to server. Sending site
 -> .htaccess c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/lib/glynn/file.
rb:5:in : No such file or directory - file c:/Users/user/desktop/folder/
_site/.htaccess (Errno::ENOENT)
       from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/lib/glynn/file.rb:5:in is_bin?'
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/li
b/glynn/ftp.rb:62:in block in send_dir  from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/li
b/glynn/ftp.rb:46:in foreach
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/li
b/glynn/ftp.rb:46:in send_dir
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/li
b/glynn/ftp.rb:17:in block in sync
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/li
b/glynn/ftp.rb:27:in block in connect
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/ftp.rb:135:in open
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/li
b/glynn/ftp.rb:23:in connect
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/li
b/glynn/ftp.rb:16:in sync
        from c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/glynn-1.2.0/bi
n/glynn:68:in <top (required)>
        from c:/RailsInstaller/Ruby2.1.0/bin/glynn:23:in load
        from c:/RailsInstaller/Ruby2.1.0/bin/glynn:23:in <main>`

**Comment by c-hris** [comment]
Still the same problem.

**Comment by dmathieu** [comment]
Well, from this stacktracem, you're definitely still running 1.2.0 and not the master branch.
I'll release 1.2.1 later this week and will let you now once it's done.

**Comment by c-hris** [comment]
I'm sorry, Im new to this i though that i install the gem from git master I didn't. I try but i guess that i dont know how.

**Comment by c-hris** [comment]
Hey it's working!! It took me a while on how to install the gem from git master, because I'm new to this but I figure out. It fixed by https://github.com/dmathieu/glynn/commit/061a538db07c90cba989ba6d1735908055c8bd28


Connected to server. Sending site
->all the files
-> more files
Successfully sent site

**Comment by dmathieu** [comment]
https://rubygems.org/gems/glynn/versions/1.2.1
