### ISSUE TITLE
Test for changed files

### ISSUE THREAD

**Issue by technatica** [dmathieu/glynn#47]
Would it be possible to have glynn test the files on the server and only overwrite them if the file for upload is newer?

**Comment by dmathieu** [comment]
Sure. I'm open to any pull requests with tests.

**Comment by vbonhomme** [comment]
I have absolutely no idea on how to do it, but I'd delighted to have it.

**Comment by lastpoke** [comment]
... and what about to delete files or folders (remote)  if they are deleted on localhost?

**Comment by dmathieu** [comment]
See #38
