### ISSUE TITLE
Read user name and password from ~/.netrc

### ISSUE THREAD

**Issue by sinisterstuf** [dmathieu/glynn#48]
I wouldn't like to paste my password into the `_config.yml` where it's publicly visible but it's also frustrating to type it out for each glynn call. I already have the password saved in `~/.netrc` because that's where other programs like vim and lftp look for it. Could glynn check that file for a user name and password defined for its host, before prompting me to enter them?

**Comment by dmathieu** [comment]
Sure. The [netrc](https://github.com/heroku/netrc) library will allow reading from `~/.netrc` and fetch the credentials.
I'm not using glynn these days and don't have visibility on when I'd be able to implement this feature. It should be fairly simple though. Feel free to do it.
