### ISSUE TITLE
Disable build

### ISSUE THREAD

**Issue by agragregra** [dmathieu/glynn#51]
Glynn build jekyll website as default option. How to disable it?

**Comment by dmathieu** [comment]
You can't, and honestly I don't think this is something we need.
It'd over-complicate things, and even if your site is already built, building it again wouldn't change anything on the file system. It would just take a few seconds more.

**Comment by agragregra** [comment]
I'm have blog with over 1000 posts & pagination? with categories fnd tags. repeated building take a lot of time - 300-400 seconds. Thanks.

**Comment by dmathieu** [comment]
You might not want to build it locally then. You can also create your own fork and implement that there.

**Comment by agragregra** [comment]
Thank you.
