### ISSUE TITLE
Error on connect

### ISSUE THREAD

**Issue by eberkund** [dmathieu/glynn#61]
I am getting this error when I try to connect. I may having something misconfigured but the error message should be more clear if it can't connect for example

    /Users/erik/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:111:in `read_timeout=': undefined method `read_timeout=' for #<TCPSocket:(closed)> (NoMethodError)
    from /Users/erik/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:963:in `ensure in close'
    from /Users/erik/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:963:in `close'
    from /Users/erik/.rvm/gems/ruby-2.2.1/gems/double-bag-ftps-0.1.2/lib/double_bag_ftps.rb:32:in `ensure in open'
    from /Users/erik/.rvm/gems/ruby-2.2.1/gems/double-bag-ftps-0.1.2/lib/double_bag_ftps.rb:32:in `open'
    from /Users/erik/.rvm/gems/ruby-2.2.1/gems/glynn-1.2.3/lib/glynn/ftp.rb:23:in `connect'
    from /Users/erik/.rvm/gems/ruby-2.2.1/gems/glynn-1.2.3/lib/glynn/ftp.rb:16:in `sync'
    from /Users/erik/.rvm/gems/ruby-2.2.1/gems/glynn-1.2.3/bin/glynn:80:in `<top (required)>'
    from /Users/erik/.rvm/gems/ruby-2.2.1/bin/glynn:23:in `load'
    from /Users/erik/.rvm/gems/ruby-2.2.1/bin/glynn:23:in `<main>'
    from /Users/erik/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/erik/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by dmathieu** [comment]
It looks like your FTP server is rejecting the connection, which prevents us from configuring it (the connection).
That looks like either invalid credentials, or an FTP server config problem.

**Comment by eberkund** [comment]
I checked my config and it works now, but what does the `ftp_secure:` value do? Is SFTP supported because I can connect via FTP on port 21 but SFTP on port 22 doesn't work.

**Comment by dmathieu** [comment]
ftp_secure uses SFTP, which is what your previous stacktrace was using (the double_bag_ftps calls).
The error happens because we can't set a read timeout on a closed socket (`#<TCPSocket:(closed)>`).

**Comment by eberkund** [comment]
Is there anything else you can think of?

I am able to connect to my server with SFTP using FileZilla so I know it works. But when I change the `ftp_port` and `ftp_secure` I get that error

**Comment by dmathieu** [comment]
Hum no. The only sure things is that this doesn't indicate a glynn bug (though we could improve the messaging around the socket being unexpectedly closed). It's the server closing or rejecting the connection.
