### ISSUE TITLE
ERROR: this appears when I open the website

### ISSUE THREAD

**Issue by Sn0wCooder** [dmathieu/glynn#62]
![schermata 2016-08-23 alle 14 50 00](https://cloud.githubusercontent.com/assets/13628230/17892311/f13d2006-6940-11e6-8805-3da4d9f322fc.png)
Any fix?

**Comment by dmathieu** [comment]
Hi,

Glynn will take the files as they are on you filesystem and upload them, nothing else.
If you have design issues showing your website, they are in your code, not in glynn.
