### ISSUE TITLE
Undefined method read_timeout= using Ruby 2.3.1 on OS X 10.11.6

### ISSUE THREAD

**Issue by ssteinerx** [dmathieu/glynn#64]
```
# glynn
Configuration file: /<my-path>/_config.yml
Building site:  /<my-path> ->  /<my-path>/_site
Configuration file: / <my-path>/_config.yml
Successfully generated site
Sending site over FTP (host: <my-site>.com, port: 21, ftps: true)
Connected to server. Sending site
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/net/ftp.rb:114:in `read_timeout=': undefined method `read_timeout=' for #<TCPSocket:(closed)> (NoMethodError)
Did you mean?  readline
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/net/ftp.rb:1175:in `ensure in close'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/net/ftp.rb:1175:in `close'
	from /usr/local/lib/ruby/gems/2.3.0/gems/double-bag-ftps-0.1.3/lib/double_bag_ftps.rb:33:in `ensure in open'
	from /usr/local/lib/ruby/gems/2.3.0/gems/double-bag-ftps-0.1.3/lib/double_bag_ftps.rb:33:in `open'
	from /usr/local/lib/ruby/gems/2.3.0/gems/glynn-1.2.3/lib/glynn/ftp.rb:23:in `connect'
	from /usr/local/lib/ruby/gems/2.3.0/gems/glynn-1.2.3/lib/glynn/ftp.rb:16:in `sync'
	from /usr/local/lib/ruby/gems/2.3.0/gems/glynn-1.2.3/bin/glynn:80:in `<top (required)>'
	from /usr/local/bin/glynn:22:in `load'
	from /usr/local/bin/glynn:22:in `<main>'
```

**Comment by ssteinerx** [comment]
Site has a valid certificate, can ssh in with same username/password.

**Comment by dmathieu** [comment]
Looks like FTP rejects the connection. Have you tried toggling the passive mode?

**Comment by ssteinerx** [comment]
Yes, no change.  This seems to indicate a bug in the ruby/2.3.0/net/ftp.rb:114:in `read_timeout=': undefined method `read_timeout=' for #<TCPSocket:(closed)> (NoMethodError) code, but I don't know enough Ruby to report it properly.

Also, should glynn be specifically catching the exception and printing out a more useful error message?  It was clear to me that the FTP connection was failing but not why and the bug stopped the exception propagating to where a more informative message may be available.

**Comment by dmathieu** [comment]
`read_timeout=` is called by `DoubleBagFTPS`, the FTPS library. They should really avoid calling that method when the connection has been closed.

**Comment by ssteinerx** [comment]
Being as the method's undefined at that point, it's a fatal error to do so and should be reported as a bug if it hasn't already.  I'm not in the Ruby world other than as an occasional visitor (read "user"), so I wouldn't be the right guy for the job...

**Comment by dmathieu** [comment]
See bnix/double-bag-ftps/pull/14
Note that this won't fix your issue per-se. This exception is actually hiding another one. But it will allow you to know what error you're actually getting.

**Comment by ssteinerx** [comment]
@dmathieu Thanks!  Hopefully they'll get that merged.
